<?php

if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_custom-loop-settings',
        'title' => 'Custom Loop settings',
        'fields' => array(
            array(
                'key' => 'field_5',
                'label' => 'Number of items to show',
                'name' => 'num_posts',
                'type' => 'text',
                'instructions' => 'Enter the number of posts you want to show.',
                'required' => 1,
                'default_value' => 3,
                'formatting' => 'none',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6',
                'label' => 'Type of content to show',
                'name' => 'custom_post_type',
                'type' => 'select',
                'instructions' => 'Select the type of content you wont to show',
                'choices' => array(
                    'project' => 'Projects',
                    'services' => 'Services',
                ),
                'default_value' => 'project',
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'project-list.php',
                    'order_no' => '0',
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_more-info-link',
        'title' => 'More Info Link',
        'fields' => array(
            array(
                'key' => 'field_534826107824d',
                'label' => 'More info',
                'name' => 'more_info',
                'type' => 'true_false',
                'instructions' => 'If this is selected then the more info link will appear in the list',
                'message' => 'Find out more?',
                'default_value' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'service',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'side',
            'layout' => 'default',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_projects',
        'title' => 'Projects',
        'fields' => array(
            array(
                'key' => 'field_51daf760f811a',
                'label' => 'Short Title',
                'name' => 'short_title',
                'type' => 'text',
                'instructions' => 'Used on the homepage for link tiltes',
                'default_value' => '',
                'formatting' => 'none',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'project',
                    'order_no' => '0',
                    'group_no' => '0',
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_service-list',
        'title' => 'Service List',
        'fields' => array(
            array(
                'key' => 'field_53482993e7519',
                'label' => 'Subtitle',
                'name' => 'sub_title',
                'type' => 'text',
                'instructions' => 'Subtitle that appears in the service list',
                'required' => 1,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_53482a0cf6fe6',
                'label' => 'Service Icon',
                'name' => 'icon',
                'type' => 'select',
                'instructions' => 'The icon that appears in the service list',
                'required' => 1,
                'choices' => array(
                    'r' => 'Responsive',
                    'w' => 'Wordpress',
                    's' => 'Shopify',
                    5 => 'HTML5',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_5bab6665eb807',
                'label' => 'Service Icon Image',
                'name' => 'service_icon_image',
                'type' => 'image',
                'instructions' => 'Add an image to use for the service',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'service',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_services',
        'title' => 'Services',
        'fields' => array(
            array(
                'key' => 'field_5347f62953e76',
                'label' => 'Service Gallery',
                'name' => 'service_gallery',
                'type' => 'repeater',
                'instructions' => 'Service sidebar Gallery',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5347f68153e77',
                        'label' => 'Image',
                        'name' => 'image',
                        'type' => 'image',
                        'instructions' => 'Upload an image',
                        'column_width' => '',
                        'save_format' => 'object',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_5347f6e353e78',
                        'label' => 'URL',
                        'name' => 'url',
                        'type' => 'text',
                        'instructions' => 'Add a url',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'http://some-url.com',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5347f73753e79',
                        'label' => 'Caption',
                        'name' => 'caption',
                        'type' => 'text',
                        'instructions' => 'Add a Caption',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Add Image',
            ),
            array(
                'key' => 'field_5348039f7db5b',
                'label' => 'Feature List Title',
                'name' => 'feature_list_title',
                'type' => 'text',
                'instructions' => 'A nice keyword title for you feature list',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5347f7b8c40f6',
                'label' => 'Feature list',
                'name' => 'feature_list',
                'type' => 'repeater',
                'instructions' => 'Add Features',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5347f7f2c40f7',
                        'label' => 'Feature',
                        'name' => 'feature',
                        'type' => 'text',
                        'instructions' => 'Add a feature',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'Something super cool',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'service',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_pages',
        'title' => 'Pages',
        'fields' => array(
            array(
                'key' => 'field_5348039f7db5b',
                'label' => 'Feature List Title',
                'name' => 'feature_list_title',
                'type' => 'text',
                'instructions' => 'A nice keyword title for you feature list',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5347f7b8c40f6',
                'label' => 'Feature list',
                'name' => 'feature_list',
                'type' => 'repeater',
                'instructions' => 'Add Features',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5347f7f2c40f7',
                        'label' => 'Feature',
                        'name' => 'feature',
                        'type' => 'text',
                        'instructions' => 'Add a feature',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'Something super cool',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
            ),
            array(
                'key' => 'field_5348039f7db5c',
                'label' => 'Additional Content',
                'name' => 'additional_content',
                'type' => 'textarea',
                'instructions' => 'Extra stuff',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'br',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_59b527705d20c',
                'label' => 'Additional Code',
                'name' => 'additional_code',
                'type' => 'textarea',
                'instructions' => 'Add some additional html or css or javascript',
                'default_value' => '',
                'placeholder' => '',
                'formatting' => 'html',
                'maxlength' => '',
                'rows' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
}